name: 自动化处理PR(Python 3.11)

on: [pull_request]

jobs:
  audit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint bandit flake8 mypy

      - name: Run Bandit
        run: |
          bandit -r . > bandit_results.txt

      - name: Run Mypy
        run: |
          mypy --ignore-missing-imports $(git ls-files '*.py') > mypy_results.txt

      - name: Analyze Loops
        run: |
          python .github/scripts/loop_analyzer.py > loop_analyzer_results.txt

      - name: Upload audit results
        uses: actions/upload-artifact@v4
        with:
          name: audit-results
          path: |
            bandit_results.txt
            flake8_results.txt
            mypy_results.txt
            loop_analyzer_results.txt

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'audit-results'  # 构件路径

      - name: Comment results to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            const results = [
              { name: 'Bandit 结果', file: 'bandit_results.txt' },
              { name: 'Mypy 结果', file: 'mypy_results.txt' },
              { name: '循环分析器结果', file: 'loop_analyzer_results.txt' },
            ];

            let commentBody = '## 代码审计结果 (Python 3.11)\n\n'; 

            for (const result of results) {
              const filePath = path.join(process.env.GITHUB_WORKSPACE, result.file);
              if (fs.existsSync(filePath)) {
                const content = fs.readFileSync(filePath, 'utf8').trim();
                if (content) {
                  commentBody += `### ${result.name}\n\`\`\`\n${content}\n\`\`\`\n\n`;
                }
              }
            }

            if (commentBody !== '## 代码审计结果 (Python 3.11)\n\n') {
              github.rest.issues.createComment({
                issue_number: context.payload.pull_request ? context.payload.pull_request.number : null, // 使用 PR 编号
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody
              });
            }