name: 自动化处理PR(Python 3.11)

on: [pull_request]

jobs:
  audit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    permissions:
      id-token: write
      contents: read
      attestations: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint bandit flake8 mypy

      - name: Run Bandit
        run: |
          bandit -r . > bandit_results.txt

      - name: Run Mypy
        run: |
          mypy --ignore-missing-imports $(git ls-files '*.py') > mypy_results.txt

      - name: Analyze Loops
        run: |
          python .github/loop_analyzer.py > loop_analyzer_results.txt

      - name: Upload audit results
        uses: actions/upload-artifact@v4
        with:
          name: audit-results-${{ runner.os }}
          path: |
            bandit_results.txt
            mypy_results.txt
            loop_analyzer_results.txt

      - name: Comment results to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            const results = [
              { name: 'Bandit 结果', file: 'bandit_results.txt' },
              { name: 'Mypy 结果', file: 'mypy_results.txt' },
            ];

            // 使用环境变量获取运行平台信息
            const platform = process.env.RUNNER_OS || '未知平台'; // 默认为 'Unknown OS' 以防变量不可用

            let commentBody = `## 代码审计结果 (Python 3.12) - 运行平台: ${platform}\n\n`; 

            for (const result of results) {
              const filePath = path.join(process.env.GITHUB_WORKSPACE, result.file);
              if (fs.existsSync(filePath)) {
                const content = fs.readFileSync(filePath, 'utf8').trim();
                if (content) {
                  commentBody += `### ${result.name}\n\`\`\`\n${content}\n\`\`\`\n\n`;
                }
              }
            }

            if (commentBody !== `## 代码审计结果 (Python 3.12) - 运行平台: ${platform}\n\n`) {
              github.rest.issues.createComment({
                issue_number: context.payload.pull_request ? context.payload.pull_request.number : null, // 使用 PR 编号
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody
              });
            }